services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: leyton_pfa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/leyton_pfa
    depends_on:
      - db

volumes:
  pgdata: